version: '3'

services:
  traefik:
    # The official v2.0 Traefik docker image
    image: traefik:v2.0
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  consul:
    build: 
      context: ./consul/
      dockerfile: Dockerfile
    container_name: consul
    volumes:
      - "./extras/consul-vault-policy.hcl:/consul/vault-policy.hcl"
      - "./consul-volume:/consul/data/"
        #    networks:
        #      - consul-network
    restart: always
    ports: 
      - "8300"
      - "8301"
      - "8302"
      - "8500"
      - "8600"

  vault:
    build:
      context: ./vault/
      dockerfile: Dockerfile
    container_name: vault
    ports:
      - "8200"
      - "8302"
      - "8500"
      - "8600"
    restart: always
    cap_add:
      - IPC_LOCK
    volumes:
      - "./vault-volume:/vault/data/"
    labels:
      - "traefik.http.routers.vault.rule=Host(`vault.docker.localhost`)"
      - "traefik.http.services.vault.loadbalancer.server.port=8200"
